---
AWSTemplateFormatVersion: '2010-09-09'
Description: Set up basic roles and policies

Resources:

  WorkshopAppSyncRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: appsync-workshop-databaserole
      Description: Role for appsync
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: appsync.amazonaws.com
          Action: sts:AssumeRole
      Policies: 
        - PolicyName: RDSPolicy 
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - rds-data:ExecuteStatement
              - rds-data:DeleteItems
              - rds-data:ExecuteSql
              - rds-data:GetItems
              - rds-data:InsertItems
              - rds-data:UpdateItems
              Resource:
              - arn:aws:rds:eu-west-1:*:cluster:*
              - arn:aws:rds:eu-west-1:*:cluster:*:*
            - Effect: Allow
              Action:
              - secretsmanager:GetSecretValue
              Resource:
              - arn:aws:secretsmanager:eu-west-1:*:secret:/workshop/hotelinventory-db-*
              - arn:aws:secretsmanager:eu-west-1:*:secret:/workshop/hotelinventory-db-:*



